#!/bin/bash
restart=true
while $restart
do
  #node /home/ors/lab/cush/server.js "$@"
  #node /home/ors/lab/cush/devserver.js "$@"
  #node --harmony --harmony_destructuring --expose_debug_as=v8debug /home/ors/lab/cush/cli.js "$@"
  node --harmony --harmony_destructuring --expose_debug_as=v8debug cli.js "$@"
  OUT=$?
  #echo "exit code: $OUT"
  if [ $OUT -eq 5 ];then
    restart=true
  else
    restart=false
  fi
done

