#!/bin/bash
restart=true
#while $restart
#do
  #debug_port=$((1000+RANDOM))
  #node /home/ors/lab/cush/server.js "$@"
  #node /home/ors/lab/cush/devserver.js "$@"
  #node --harmony --harmony_destructuring --expose_debug_as=v8debug /home/ors/lab/cush/cli.js "$@"
  #node --harmony --harmony_destructuring_assignment --debug --expose_debug_as=v8debug ~/lab/cush/cli.js "$@"
  #node --harmony_shipping --harmony_destructuring_assignment --debug=$debug_port --expose_debug_as=v8debug ~/lab/cush/cli.js "$@"
  node --harmony_shipping ~/dev/cush/cli.js "$@"
  #node-debug --harmony --harmony_destructuring_assignment --expose_debug_as=v8debug ~/lab/cush/cli.js "$@"
  OUT=$?
  echo "cush server exit code: $OUT"
  #if [ $OUT -eq 8 ];then
  if [ $OUT -eq 143 ];then
    echo '---------- reset --------------'
    . $0 "$@"
  else

    #################################
    echo '---------- wait... --------------'
    inotifywait -qq  -e modify $0 ~/dev/cush/** ~/dev/cush/server/** ~/dev/cush/server/responders/** ~/mod/**

    echo '---------- restart --------------'
    . $0 "$@"
  #else
    #restart=false
  fi
#done

